### ISSUE TITLE
Add "vs-md" and "vs-xl" to Grid layout

### ISSUE THREAD

**Issue by julienperrault** [lusaxweb/vuesax#952]
**Is your feature request related to a problem? Please describe.**
Hello,
I use "vue-sax" with "tailwindcss" and I just found out that the vue-sax grid layout doesn't support intermediate size (md) and larger size (xl). 

Here is a table of supported sizes according to frameworks

Size|[vue-sax](https://lusaxweb.github.io/vuesax/layout/#responsive-layout) (and [vue-sax-next](https://vuesax.com/docs/layout/#responsive))|[tailwindcss](https://tailwindcss.com/docs/responsive-design)|[bootstrap 4](https://getbootstrap.com/docs/4.0/layout/grid/#grid-options)|[flexboxgrid](http://flexboxgrid.com)
| --- | --- | --- | --- | --- |
<576px|`vs-xs`| [nothing planned because "Mobile first"](https://tailwindcss.com/docs/responsive-design#mobile-first)|`.col-`|`.col-xs-`
≥576px|`vs-sm`|`sm:`|`.col-sm-`|`.col-sm-`
≥768px| **NOTHING** |`md:`|`.col-md-`|`.col-md-`
≥992px|`vs-lg`|`lg:`|`.col-lg-`|`.col-lg-`
≥1200px| **NOTHING** |`xl:`|`.col-xl-`|`.col-xl-`
≥1536px| nothing |`2xl:`| nothing | nothing

**Describe the solution you'd like**
The solution I suggest would be to add the two rules "vs-md" and "vs-xl" in both projects (vue-sax and vue-sax-next)

**Describe alternatives you've considered**
Create on my projects, "by hand", the two missing rules.
Workaround (SCSS) : 
```scss
@mixin vs-md-xl-x {
  $columns: 12;
  $one-width: 1/$columns;
  @for $i from 1 through $columns {
    @media (min-width: 768px) and (max-width: 992px) {
      .vs-md-#{$i} {
        width: percentage($i * $one-width)+unquote('!important');
      }
    }
    @media (min-width: 1200px) {
      .vs-xl-#{$i} {
        width: percentage($i * $one-width)+unquote('!important');
      }
    }
  }
}
@include vs-md-xl-x;
```
